engine:
  timeout: 120
  asyncTimeout: 1000
  version: ${version:UNKNOWN}
cloud:
  api: ${sso.apiEndpoint}
  clientId: ${sso.clientId}
  clientPassword: ${sso.clientSecret}
  uaa: ${sso.uaaUri}
zookeeper:
  clusterUrl: ${zk.cluster.url:}
  user: ${zk.user:authgateway}
  password: ${zk.password:authgateway}
  node: ${zk.node:/auth-gateway}
kerberos:
  user: ${krb.user:}
  keytab: ${krb.keytab.path:}
  kdc: ${krb.kdc:}
  realm: ${krb.realm:}
  enabled: ${krb.enabled:false}
hbase:
  configPath: ${hbase.config.path}
hive:
  configPath: ${hive.config.path}
yarn:
  cloudera:
    user: ${cloudera.user:}
    password: ${cloudera.password:}
    url: ${cloudera.address:}
    store: ${cloudera.truststore:}
    storePassword: ${cloudera.truststore.password:}
group.mapping:
  supergroup: ${hgm.supergroup:supergroup}
  url: ${hgm.url}
  kerberos:
    principal: ${hgm.principal:}
    keytabPath: ${hgm.principal.keytab.path:}
  https:
    username: ${hgm.username:}
    password: ${hgm.password:}
sentry.server:
  address: ${sentry.address:}
  port: ${sentry.port:8038}
  principal: ${sentry.principal:sentry}
impala.server:
  connectionUrl: ${impala.connectionUrl:}
  available: ${impala.available}
hive.server:
  connectionUrl: ${hive.connectionUrl}
  hdfsUri: ${hive.hdfsUri:hdfs://nameservice1/org/}
warehouse.client:
  keytabPath: ${warehouse.keytab.path:}
  superUser: ${warehouse.superuser:hive}
spring.oauth2.resource:
  id: ${resource.id:tap}
  jwt:
    keyUri: ${sso.tokenKey}
logging.level:
  org.apache.zookeeper: INFO
  org.trustedanalytics: INFO
endpoints:
  health.enabled: true
hdfs:
  hiveUser: ${hdfs.hiveuser:}
  cfUser: ${hdfs.cfuser:cf}
  arcadiaUser: ${hdfs.arcadiauser:arcadia-user}
  vcapUser: ${hdfs.vcapuser:vcap}
  configPath: ${hdfs.config.path}
  structure:
    base:
      - path: /user/broker
        permissions: drwx------
        user: broker
        group: broker
      - path: /user/h2o
        permissions: drwx------
        user: h2o
        group: h2o
      - path: /org
        permissions: drwx--x--x
        user: authgateway
        group: supergroup
    org:
      root:
        path: /org/{org}
        permissions: drwxrwx---
        acl:
          - user:broker:--x
          - group:hive:r-x
      user:
        path: /org/{org}/user/{user}
        permissions: drwx------
      dirs:
        - path: apps
          permissions: drwxr-x---
        - path: user
          permissions: drwxr-x---
        - path: shared
          permissions: drwxrwx---
        - path: tmp
          permissions: drwxrwx---
        - path: jars
          permissions: drwxrwx---
          acl:
            - user:broker:rwx
        - path: oozie-jobs
          permissions: drwxrwx---
        - path: brokers
          permissions: drwxrwx---
          acl:
            - user:broker:rwx
            - group:hive:rwx
        - path: brokers/userspace
          permissions: drwxrwx---
          acl:
            - user:broker:rwx
            - group:hive:rwx
        - path: datasets
          permissions: drwxrwx---
          acl:
            - user:broker:rwx
            - group:hive:rwx
        - path: sqoop-imports
          permissions: drwxrwx---
          acl:
            - user:broker:rwx
            - group:hive:rwx

